USE Despesas
GO

CREATE PROCEDURE sp_FazerLogin @EMAIL VARCHAR(50), @SENHA VARCHAR(50)
AS

BEGIN TRY
	DECLARE @ID_USUARIOS INT = 0, @NOME_USUARIO VARCHAR(50) = ''

	SELECT @ID_USUARIOS = ID_USUARIOS, @NOME_USUARIO = NOME_USUARIO
	FROM Usuarios
	WHERE (EMAIL = @EMAIL) AND (SENHA = @SENHA)

	SELECT @ID_USUARIOS AS ID_USUARIOS, @NOME_USUARIO AS NOME_USUARIO
END TRY


-- tratando erros;
BEGIN CATCH
	DECLARE @ERRO_COMPLETO VARCHAR(2000)

	SET @ERRO_COMPLETO = CONCAT(
		'Número do Erro: ',			ERROR_NUMBER(),			CHAR(13),
		'Descrição do Erro: ',		ERROR_MESSAGE(),		CHAR(13),
		'Severidade do Erro: ',		ERROR_SEVERITY(),		CHAR(13),
		'Nome do procedimento: ',	ERROR_PROCEDURE(),		CHAR(13),
		'Linha do Error: ',			ERROR_LINE(),			CHAR(13))

	DECLARE @ESTADO INT = ERROR_STATE();

	THROW 50000, @ERRO_COMPLETO, @ESTADO
END CATCH


/*
EXEC sp_FazerLogin @EMAIL = 'luiz@email.com', @SENHA = 'Luiz@123'

SELECT * FROM Usuarios
*/